server:
    port: 8090

logging:
    level:
      org.hibernate.sql: DEBUG
      org.hibernate.engine.transaction: DEBUG
spring:
    application:
        name: national-office-test

    datasource:
        url: jdbc:postgresql://localhost:5434/national_office
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 100



    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: none

        show-sql: true

